name: Etheria CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Get JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Git Config
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches
      - name: Create Paperclip Jar
        run: ./gradlew createReobfPaperclipJar
      - name: Get Release Info
        run: sh scripts/GetReleaseInfo.sh
      - name: Create Release
        if: "contains(github.event.commits[0].message, '[release]')"
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: ${{ env.jar }}
          bodyFile: ${{ env.info }}
          tag: ${{ env.tag }}
          name: ${{ env.name }}
          prerelease: ${{ env.pre }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: ${{ env.make_latest }}
      - name: Github Releases To Discord
        if: "contains(github.event.commits[0].message, '[release]')"
        continue-on-error: true
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          raw-data: ${{ env.discordmes }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.jar }}
          path: ${{ env.jar }}
      - name: Publish Api
        run: ./gradlew publish -PsubkekUsername=${{ secrets.REPO_USERNAME }} -PsubkekPassword=${{ secrets.REPO_PASSWORD }}
