name: Etheria CI
on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - name: Get repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Git Config
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches
      - name: Create Paperclip Jar
        run: ./gradlew createReobfPaperclipJar

  get-release-info:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Release Info
        run: sh scripts/GetReleaseInfo.sh

  create-release:
    runs-on: ubuntu-latest
    needs: get-release-info
    if: "contains(github.event.commits[0].message, '[release]')"
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: ${{ env.jar }}
          bodyFile: ${{ env.info }}
          tag: ${{ env.tag }}
          name: ${{ env.name }}
          prerelease: ${{ env.pre }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: ${{ env.make_latest }}

  notify-discord:
    runs-on: ubuntu-latest
    needs: create-release
    if: "contains(github.event.commits[0].message, '[release]')"
    steps:
      - name: Github Releases To Discord
        continue-on-error: true
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          raw-data: ${{ env.discordmes }}

  upload-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.jar }}
          path: ${{ env.jar }}

  publish-api:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish Api
        run: ./gradlew publish -PsubkekUsername=${{ secrets.REPO_USERNAME }} -PsubkekPassword=${{ secrets.REPO_PASSWORD }}
